# Generated by Django 6.0.2 on 2026-02-28 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='video_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
